name: Validacion Continua - Clinica Andina

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analisis_y_construccion:
    runs-on: ubuntu-latest

    steps:
    - name: Extraccion del repositorio fuente
      uses: actions/checkout@v4

    - name: Aprovisionamiento del SDK .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Resolucion de dependencias (NuGet)
      run: dotnet restore

    - name: Compilacion de artefactos (Release)
      run: dotnet build --no-restore --configuration Release

    - name: Evaluacion de pruebas unitarias
      run: dotnet test --no-build --verbosity normal --configuration Release